# Generated by Django 5.2.6 on 2025-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the studnt name', max_length=250)),
                ('age', models.IntegerField(help_text='Enter the age between 18 to 22')),
                ('dob', models.DateField(help_text='Enter the Date of Birth')),
                ('reg_no', models.IntegerField(help_text='Enter the Register Number')),
            ],
        ),
    ]
